export const catPortfolioData = {
  meta: {
    concept: "Cat Portfolio",
    ownerCredit: "Made with love by yewon.cc",
    ownerSite: "https://yewon.cc",
    ownerSiteLabel: "yewon.cc",
    ownerTistory: "https://parkdohyun.tistory.com/",
    ownerYoutube: "https://www.youtube.com/@Mr.Share_Man",
    ownerLinkedin: "https://linkedin.com/in/dohyunbak",
    dedication: "This website is dedicated to my lovely cat.",
  },
  profile: {
    name: "임자",
    tagline: "햇살 좋은 자리와 조용한 오후를 수집하는 고양이",
    intro:
      "차분한 눈빛으로 집 안의 모든 루틴을 관리하고, 가장 따뜻한 곳을 누구보다 빨리 찾아내는 작은 동거인.",
    tags: ["#집사감시관", "#낮잠전문가", "#간식헌터", "#창밖관찰자"],
    heroImage:
      "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=1200&q=85",
    heroImageAlt: "따뜻한 빛을 받으며 앉아 있는 고양이",
    summaryCards: [
      { id: "age", label: "나이", value: "3살", note: "호기심은 아직 아기" },
      { id: "personality", label: "성격", value: "차분 + 장난", note: "낯은 가리지만 마음은 큼" },
      { id: "snack", label: "좋아하는 간식", value: "닭가슴살", note: "봉지만 봐도 출석" },
      { id: "mood", label: "오늘의 기분", value: "매우 여유", note: "창가 근무 중" },
    ],
    details: [
      { id: "name", label: "이름", value: "임자", icon: "paw" },
      { id: "age", label: "나이", value: "3살", icon: "cake" },
      { id: "breed", label: "품종", value: "코리안 숏헤어", icon: "badge" },
      { id: "gender", label: "성별", value: "여아", icon: "user" },
      { id: "nickname", label: "별명", value: "임대리, 감시반장", icon: "sparkles" },
      { id: "personality", label: "성격", value: "조심스럽지만 다정함", icon: "heart" },
      { id: "favoriteSnack", label: "좋아하는 간식", value: "닭가슴살, 동결건조 트릿", icon: "coffee" },
      { id: "favoritePlace", label: "좋아하는 장소", value: "거실 창가, 노트북 옆", icon: "home" },
      { id: "hospital", label: "자주 다니는 병원", value: "청계동물종합병원", icon: "stethoscope" },
      { id: "ownerSite", label: "주인의 사이트", value: "yewon.cc", icon: "globe" },
    ],
  },
  stats: [
    { id: "affection", label: "애교도", score: 82, note: "먼저 오지는 않지만 옆자리는 지킴" },
    { id: "playful", label: "장난기", score: 76, note: "끈 장난감 한정 집중력 상승" },
    { id: "appetite", label: "식탐", score: 91, note: "간식 서랍 소리에 즉시 반응" },
    { id: "sleep", label: "잠자는 시간", score: 88, note: "하루 대부분을 품격 있게 충전" },
    { id: "zoomies", label: "우다다력", score: 67, note: "밤 8시 이후 짧고 강함" },
    { id: "supervision", label: "집사 감시력", score: 94, note: "화장실과 부엌 동선까지 확인" },
  ],
  gallery: [
    {
      id: "sun-window",
      title: "창가 근무",
      caption: "햇살이 들어오는 시간에는 자리 양보가 필요합니다.",
      src: "https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&w=900&q=85",
      alt: "창가 근처에 앉아 있는 고양이",
      featured: true,
    },
    {
      id: "quiet-look",
      title: "조용한 눈빛",
      caption: "말은 없지만 모든 것을 알고 있는 표정.",
      src: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=700&q=85",
      alt: "카메라를 바라보는 고양이 얼굴",
    },
    {
      id: "blanket",
      title: "담요 점령",
      caption: "따뜻한 담요는 자동으로 임자 소유가 됩니다.",
      src: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=700&q=85",
      alt: "담요 위에서 쉬고 있는 고양이",
    },
    {
      id: "nap",
      title: "오후 낮잠",
      caption: "가장 조용한 방에서 가장 길게 자는 시간.",
      src: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=700&q=85",
      alt: "편안하게 누워 자는 고양이",
    },
    {
      id: "portrait",
      title: "대표 증명사진",
      caption: "집사의 앨범에 가장 많이 저장된 각도.",
      src: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?auto=format&fit=crop&w=700&q=85",
      alt: "부드러운 배경 앞의 고양이 초상",
    },
    {
      id: "stretch",
      title: "기상 스트레칭",
      caption: "일어나자마자 하는 짧은 준비 운동.",
      src: "https://images.unsplash.com/photo-1543852786-1cf6624b9987?auto=format&fit=crop&w=700&q=85",
      alt: "몸을 길게 펴고 있는 고양이",
    },
    {
      id: "curious",
      title: "검사 중",
      caption: "새 물건은 반드시 냄새 검사를 통과해야 합니다.",
      src: "https://images.unsplash.com/photo-1478098711619-5ab0b478d6e6?auto=format&fit=crop&w=700&q=85",
      alt: "호기심 있게 주변을 살피는 고양이",
    },
    {
      id: "sofa",
      title: "소파 관리자",
      caption: "가장 폭신한 쿠션의 위치를 기억합니다.",
      src: "https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=700&q=85",
      alt: "소파 위에 앉아 있는 고양이",
    },
    {
      id: "closeup",
      title: "근접 기록",
      caption: "수염과 눈빛까지 남겨두고 싶은 순간.",
      src: "https://images.unsplash.com/photo-1511044568932-338cba0ad803?auto=format&fit=crop&w=700&q=85",
      alt: "고양이 얼굴을 가까이 촬영한 사진",
    },
  ],
  routine: [
    { time: "07:00", title: "집사 깨우기", description: "침대 주변 순찰 후 조용한 알람 역할을 시작합니다." },
    { time: "08:00", title: "아침밥 먹기", description: "그릇 앞 대기 시간이 가장 정확한 스케줄입니다." },
    { time: "10:00", title: "창밖 구경", description: "새와 햇빛, 지나가는 사람까지 차분하게 관찰합니다." },
    { time: "13:00", title: "낮잠", description: "거실과 방을 오가며 최적의 온도를 찾습니다." },
    { time: "20:00", title: "우다다", description: "짧게 뛰고 멈춘 뒤 아무 일 없었다는 얼굴을 합니다." },
    { time: "23:00", title: "집사 옆에서 자기", description: "하루의 마지막은 가장 가까운 자리에서 마무리합니다." },
  ],
  memories: [
    {
      date: "2021.04",
      title: "처음 만난 날",
      description: "낯선 공간에서도 조심스럽게 눈을 맞추던 첫 순간을 아직 기억합니다.",
    },
    {
      date: "2021.05",
      title: "처음 집에 온 날",
      description: "소파 아래를 탐색하던 시간이 지나고, 창가를 가장 좋아하는 자리로 정했습니다.",
    },
    {
      date: "2022.09",
      title: "가장 귀여웠던 사건",
      description: "새 장난감을 보고 놀란 척하다가, 결국 밤새 혼자 놀던 날.",
    },
    {
      date: "2024.01",
      title: "기억에 남는 사진",
      description: "햇빛이 얼굴에 닿은 오후 사진이 가족 모두의 배경화면이 되었습니다.",
    },
    {
      date: "최근",
      title: "최근 근황",
      description: "간식 서랍 감시 능력이 더 정교해졌고, 노트북 옆자리를 자주 요구합니다.",
    },
  ],
};
